:---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install curl
      package:
         name:
          - curl
          - htop


 -name: copy wallpaper file
  copy:
    src: file/wallpapaer.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    group: root
    group: root
